### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by Haasie** [jaynguyens/obsidian-ghost-publish#2]
Hello, 
Ive tried to get the plugin working but without success.
Ive build it with NPM, placed in the right directory, rebooted the app. 
Plugin appears in the community plugin list an is enabled. url and key are paste, reboot the app again, pushed on publish but nothing happens.

**Comment by jaynguyens** [comment]
Just realise that the url need to be `https://domain.com`, with just `domain.com` it won't work. Let's me know if it works for you, if it not work `View -> Toggle Developer Tools` and send me what error it said on there.

**Comment by jaynguyens** [comment]
Gotcha, my bad - don't have time for documentation yet. I'll try to do it asap. And a bug - it should able to read your file name and use it as post title.

But for now, I would recommend you to add a frontmatter to your post.
Try follow this format. 
```
title: string
tags: 
- tag1
- tag2
featured: boolean
published: boolean
excerpt: string
```

So bare minimum, add this at the top of your post and it should work:
```
title: hello world
```

**Comment by Haasie** [comment]
Tested and can confirm it worked.
